### ISSUE TITLE
Request: add some <table> styling

### ISSUE THREAD

**Issue by marcelstoer** [MachoThemes/Decode#48]
It'd be nice if you could include some minimal table styling by default. The table on http://frightanic.com/iot/comparison-of-esp8266-nodemcu-development-boards/ is barely noticeable as such.

Even better would be if the theme could be customized to use 1 of several table presets.

**Comment by marcelstoer** [comment]
I eventually decided to go with Bootstrap CSS to style my tables. It fits quite nicely into Decode. The following adds support for striped tables:

```css
/*Bootstrap table CSS, http://getbootstrap.com/css/#tables-striped*/
.table {
  width: 100%;
  max-width: 100%;
  margin-bottom: 20px;
}
table {
  background-color: transparent;
}
table {
  border-spacing: 0;
  border-collapse: collapse;
}
th {
  text-align: left;
}
td, th {
  padding: 0;
}
.table-striped>tbody>tr:nth-of-type(odd) {
  background-color: #f9f9f9;
}
.table>caption+thead>tr:first-child>td, .table>caption+thead>tr:first-child>th, .table>colgroup+thead>tr:first-child>td, .table>colgroup+thead>tr:first-child>th, .table>thead:first-child>tr:first-child>td, .table>thead:first-child>tr:first-child>th {
  border-top: 0;
}
.table>thead>tr>th {
  vertical-align: bottom;
  border-bottom: 2px solid #ddd;
}
.table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
  padding: 8px;
  line-height: 1.42857143;
  vertical-align: top;
  border-top: 1px solid #ddd;
}
```
